name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: step1
      env:
        mysecret : ${{ secrets.sec1 }}
      run: |
          echo "helloworld!"
          if [ "$MYSECRET" = "testtest" ]; then
            echo "In testing correct secret!"
          fi
